Import Debian changes 1:1.6.6-2
makedumpfile (1:1.6.6-2) unstable; urgency=medium

  [ Guilherme G. Piccoli ]
  * Add kdump retry/delay mechanism when dumping over network

  [ Thadeu Lima de Souza Cascardo ]
  * Use a different service for vmcore dump.
  * Use maxcpus instead of nr_cpus on ppc64el.
  * Reload kdump when CPU is brought online.
  * Allow proper reload of kdump after multiple hotplug events.

diff --git a/debian/kdump-config.in b/debian/kdump-config.in
--- a/debian/kdump-config.in
+++ b/debian/kdump-config.in
@@ -50,6 +50,8 @@ KDUMP_DIR="/var/lib/kdump"
 KDUMP_NUM_DUMPS=${KDUMP_NUM_DUMPS:=0}
 NFS_TIMEO=${NFS_TIMEO:=600}
 NFS_RETRANS=${NFS_RETRANS:=3}
+NFS_MOUNT_RETRY=${NFS_MOUNT_RETRY:=4}
+SSH_KDUMP_RETRY=${SSH_KDUMP_RETRY:=16}
 MAKEDUMP_ARGS=${MAKEDUMP_ARGS:="-c -d 31"}
 KDUMP_CMDLINE_APPEND=${KDUMP_CMDLINE_APPEND:="@KDUMP_CMDLINE_APPEND@"}
 KDUMP_KERNEL_HOOK="/etc/kernel/postinst.d/kdump-tools"
@@ -647,8 +649,21 @@ function kdump_save_core()
 	#
 	if [ -n "$NFS" ];then
 		log_action_msg "Mounting NFS mountpoint $NFS ..."
-		mount -t nfs -o nolock -o tcp -o soft -o timeo=${NFS_TIMEO} -o retrans=${NFS_RETRANS} $NFS $KDUMP_COREDIR
-		ERROR=$?
+		MOUNTOPTS="-o nolock -o tcp -o soft -o timeo=${NFS_TIMEO} -o retrans=${NFS_RETRANS}"
+
+		CNT=${NFS_MOUNT_RETRY}
+		while [ $CNT -ne 0 ];do
+			mount -t nfs $MOUNTOPTS $NFS $KDUMP_COREDIR
+			ERROR=$?
+			if [ $ERROR -eq 0 ];then
+				CNT=0
+			else
+				((CNT--))
+				log_action_msg "Network not reachable; will try $CNT more times"
+				sleep 3
+			fi
+		done
+
 		if [ $ERROR -ne 0 ];then
 			log_failure_msg "$NAME: Unable to mount remote NFS directory $NFS. Cannot save core"
 			logger -t $NAME "Unable to mount remote NFS directory $NFS. Cannot save core"
@@ -759,14 +774,23 @@ function kdump_save_core_to_ssh()
 	KDUMP_COREFILE="$KDUMP_STAMPDIR/dump.$KDUMP_STAMP"
 	KDUMP_TMPDMESG="/tmp/dmesg.$KDUMP_STAMP"
 	KDUMP_DMESGFILE="$KDUMP_STAMPDIR/dmesg.$KDUMP_STAMP"
-	ERROR=0
 
-	ssh -i $KDUMP_SSH_KEY $KDUMP_REMOTE_HOST mkdir -p $KDUMP_STAMPDIR
-	ERROR=$?
-	# If remote connections fails, no need to continue
-	if [ $ERROR -ne 0 ] ; then
-		log_failure_msg "$NAME: Unable to reach remote server $KDUMP_REMOTE_HOST. No reason to continue"
-		logger -t $NAME "Unable to reach remote server $KDUMP_REMOTE_HOST. No reason to continue"
+	CNT=${SSH_KDUMP_RETRY}
+	while [ $CNT -ne 0 ];do
+		ssh -i $KDUMP_SSH_KEY $KDUMP_REMOTE_HOST mkdir -p $KDUMP_STAMPDIR
+		ERROR=$?
+		if [ $ERROR -eq 0 ];then
+			CNT=0
+		else
+			((CNT--))
+			log_action_msg "Network not reachable; will try $CNT more times"
+			sleep 3
+		fi
+	done
+
+	if [ $ERROR -ne 0 ]; then
+		log_failure_msg "$NAME: Unable to reach remote server $KDUMP_REMOTE_HOST; can't continue"
+		logger -t $NAME "Unable to reach remote server $KDUMP_REMOTE_HOST; can't continue"
 		return 1
 	fi
 
