Import Debian changes 1:1.5.3-2
makedumpfile (1:1.5.3-2) unstable; urgency=medium

  * Adapt to kernel 3.16 changes in symbols :
    - Work around removal of struct vmlist in kernel 3.16
    - Fix dump_dmesg accordingly
    - Backported commits are : 759b78c, cee64e3, 8145e41, e203095,
      150b58eb, 846ab2e, 1202589, 8a0236c, 9d38132, e24dc53
    Closes: #719943
  * Implement systemd service and correct mechanism
    to capture kernel dumps under systemd control
    Closes: #771210

diff --git a/debian/kdump-config b/debian/kdump-config
--- a/debian/kdump-config
+++ b/debian/kdump-config
@@ -24,7 +24,6 @@
 #	* unloading a kdump kernel
 #	* saving a vmcore kdump kernel
 #	* determining the status of kdump
-#	* propagate ssh key to remote host
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 NAME=${NAME:="kdump-config"}
@@ -45,9 +44,7 @@ ARCH=`uname -m`
 # Set up defaults
 KDUMP_SYSCTL=${KDUMP_SYSCTL:="kernel.panic_on_oops=1"}
 KDUMP_COREDIR=${KDUMP_COREDIR:=/var/crash}
-KDUMP_DUMP_DMESG=${KDUMP_DUMP_DMESG:=1}
-MAKEDUMP_ARGS=${MAKEDUMP_ARGS:="-c -d 31"}
-KDUMP_CMDLINE_APPEND=${KDUMP_CMDLINE_APPEND:="irqpoll maxcpus=1 nousb"}
+KDUMP_CMDLINE_APPEND=${KDUMP_CMDLINE_APPEND:="irqpoll maxcpus=1 nousb systemd.unit=kdump-tools.service"}
 [ -d $KDUMP_COREDIR ] || mkdir -p $KDUMP_COREDIR ;
 
 IOMEM_ADDR=`grep -i "Crash kernel" /proc/iomem | sed "s/-..*//" | sed "s/^[ 0]*/0x/"`
@@ -55,6 +52,9 @@ IOMEM_ADDR=`grep -i "Crash kernel" /proc/iomem | sed "s/-..*//" | sed "s/^[ 0]*/
 # Constants
 vmcore_file=/proc/vmcore
 sys_kexec_crash=/sys/kernel/kexec_crash_loaded
+kernel_link=$KDUMP_COREDIR/kernel_link
+systemmap_link=$KDUMP_COREDIR/system.map_link
+kconfig_link=$KDUMP_COREDIR/config_link
 kexec_cmd_file=$KDUMP_COREDIR/kexec_cmd
 
 # Utility Functions
@@ -63,18 +63,17 @@ function kdump_help()
 {
 cat <<EOHELP
 Usage:
-kdump-config {help|test|show|status|load|unload|savecore|propagate}"
-  help      - print this page
-  test      - Do a dry-run of the load command.  Show the kernels and
-              parameters that will be used and echo the kexec command.
-              The kexec command will not be executed.
-  show      - Show kdump status, kexec command, and any current parameters.
-  status    - evaluate /sys/kernel/kexec_crash_loaded and print a message
-  load      - Locate the kdump kernel, debug kernel, and establish links for
-              makedumpfile.  Then load the kdump kernel using kexec
-  unload    - unload the kdump kernel using kexec
-  savecore  - use previously made links to save /proc/vmcore
-  propagate - Send public ssh key to remote host for passwordless connection
+kdump-config {help|test|show|status|load|unload|savecore}"
+  help     - print this page
+  test     - Do a dry-run of the load command.  Show the kernels and
+             parameters that will be used and echo the kexec command.
+             The kexec command will not be executed.
+  show     - Show kdump status, kexec command, and any current parameters.
+  status   - evaluate /sys/kernel/kexec_crash_loaded and print a message
+  load     - Locate the kdump kernel, debug kernel, and establish links for
+             makedumpfile.  Then load the kdump kernel using kexec
+  unload   - unload the kdump kernel using kexec
+  savecore - use previously made links to save /proc/vmcore
 
 EOHELP
 }
@@ -85,26 +84,14 @@ function kdump_show()
 	echo "KDUMP_SYSCTL:     $KDUMP_SYSCTL"
 	echo "KDUMP_COREDIR:    $KDUMP_COREDIR"
 	echo "crashkernel addr: $IOMEM_ADDR"
-
-	if [ -n "$SSH" ];then
-		echo "SSH:              $SSH"
-		SSH_KEY="${SSH_KEY:=/root/.ssh/kdump_id_rsa}"
-		echo "SSH_KEY:          $SSH_KEY"
-	fi
-	if [ -n "$NFS" ]; then
-		echo "NFS:              $NFS"
-	fi
-
-	if [ -n "$SSH" ] || [ -n "$NFS" ]; then
-		HOSTTAG="${HOSTTAG:=ip}"
-		echo "HOSTTAG:          $HOSTTAG"
-	fi
-
 	if [ -e $sys_kexec_crash -a `cat $sys_kexec_crash` -eq 1 ] ; then
 		echo "current state:    ready to kdump";
 	else
 		echo "current state:    Not ready to kdump";
 	fi
+	echo
+	echo "kernel link: "
+	echo "  "`readlink -n -s $kernel_link`
 	echo
 	echo "kexec command:"
 	echo -n "  "
@@ -126,6 +113,8 @@ function kdump_test()
 	echo "   $KDUMP_KERNEL"
 	echo "kdump initrd: "
 	echo "  $KDUMP_INITRD"
+	echo "debug kernel: "
+	echo "  $DEBUG_KERNEL"
 	echo "kexec command to be used:"
 	echo "  $KEXEC_CMD"
 }
@@ -153,10 +142,6 @@ function check_kdump_support()
 		log_failure_msg "no crashkernel= parameter in the kernel cmdline"
 		[ ! $DRY_RUN ] && exit 1;
 	fi
-        if [ -n "$NFS" ] && [ -n "$SSH" ];then
-		log_failure_msg "\$SSH and \$NFS cannot be defined concurrently"
-		[ ! $DRY_RUN ] && exit 1;
-	fi
 }
 
 # check_relocatable: check if the given kernel config is relocatable
@@ -166,7 +151,7 @@ function check_kdump_support()
 #          1 otherwise.
 function check_relocatable()
 {
-	if [ "$ARCH" = "ia64" ]; then
+	if [ $ARCH = "ia64" ]; then
 		# Linux is always relocatable on ia64
 		return 0
 	elif grep -q 'CONFIG_RELOCATABLE=y' $1; then
@@ -174,6 +159,75 @@ function check_relocatable()
 	else
 		return 1
 	fi
+}
+
+# We need to find debug kernel for makedumpfile file to use when 
+# processing the vmcore file.  This will 
+#   A) speed up the vmcore copy and 
+#   B) make it much smaller (see A).
+# When the kdump kernel boots, we have no idea what kernel just 
+# dumped, so we should determine this info whenever a normal (non-kdump) 
+# kernel boots.
+#
+# Use the following priorites in determining the debug kernel:
+#	 1. An explicit Debug kernel in the defaults file overrides all
+#	 2. Look for an installed debug kernel matching the current `uname -r`
+# 	 3. Give up.  Note, that a debug kernel is optional.
+#
+# Returns: 0/1 (success/fail)
+# Sets:    MAKEDUMP_CONFIG, DEBUG_KERNEL, DEBUG_CONFIG, DEBUG_MAP
+function locate_debug_kernel()
+{
+	MAKEDUMP_CONFIG=$KDUMP_COREDIR/makedump-config-$KVER
+
+	# 1: Is there an Explicit DEBUG_KERNEL in the defaults file?
+	if [ -n "$DEBUG_KERNEL" ] ; then
+		if [ ! -e "$DEBUG_KERNEL" ] ; then
+			log_failure_msg "$KDUMP_DEFAULTS: DEBUG_KERNEL " \
+				"does not exist: $DEBUG_KERNEL"
+			logger -t $NAME "$KDUMP_DEFAULTS: DEBUG_KERNEL " \
+				"does not exist: $DEBUG_KERNEL"
+			return 1;
+		fi
+
+	# 2: Look for an installed debug kernel
+	elif [ -e /usr/lib/debug/boot/vmlinux-$KVER ] ; then
+		DEBUG_KERNEL=/usr/lib/debug/boot/vmlinux-$KVER
+		DEBUG_CONFIG=/boot/config-$KVER
+		DEBUG_MAP=/boot/System.map-$KVER
+	elif [ -e /usr/lib/debug/vmlinux-$KVER ] ; then
+		DEBUG_KERNEL=/usr/lib/debug/vmlinux-$KVER
+		DEBUG_CONFIG=/usr/lib/debug/config-$KVER
+		DEBUG_MAP=/usr/lib/debug/System.map-$KVER
+
+	# FIXME: Look for a vmcoreinfo file
+
+	# 3: give up :)
+	else
+		echo "Could not find an installed debug vmlinux image and"
+		echo "DEBUG_KERNEL is not specified in $KDUMP_DEFAULTS"
+		log_warning_msg "makedumpfile may be limited to -d 1"
+		return 1;
+	fi
+
+	if [ $DRY_RUN ] ; then return 0; fi
+
+	# Okay, now we know the name of the debug kernel and it exists...
+	if [ -e "$DEBUG_KERNEL" ] ; then
+
+		rm -f $kernel_link $systemmap_link $kconfig_link
+		# Create Links to the stuff to preserve what we found.
+		# The kdump kernel won't be able to determine this on its own.
+		[ -e "$DEBUG_KERNEL" ] && ln -s $DEBUG_KERNEL $kernel_link
+		[ -e "$DEBUG_MAP" ]    && ln -s $DEBUG_MAP    $systemmap_link
+		[ -e "$DEBUG_CONFIG" ] && ln -s $DEBUG_CONFIG $kconfig_link
+
+		return 0;
+	fi
+
+	# This can't actually be reached...
+	log_failure_msg "Warning: no debug kernel found"
+	return 1;
 }
 
 # Find the kexec/kdump kernel and possibly a corresponding initrd.
@@ -205,13 +259,7 @@ function locate_kdump_kernel()
 	# 2: The currently running kernel may be relocatable.  If so, then
 	#    use the currently running kernel as the crash kernel.
 	if check_relocatable /boot/config-$KVER; then
-		if [ -f /boot/vmlinuz-$KVER ]; then
-			KDUMP_KERNEL=/boot/vmlinuz-$KVER
-		elif [ -f /boot/vmlinux-$KVER ]; then
-			KDUMP_KERNEL=/boot/vmlinux-$KVER
-		else
-			KDUMP_KERNEL=
-		fi
+		KDUMP_KERNEL=/boot/vmlinuz-$KVER
 		if [ -f /boot/initrd.img-$KVER ]; then
 			KDUMP_INITRD=/boot/initrd.img-$KVER
 		else
@@ -231,7 +279,7 @@ function locate_kdump_kernel()
 	else
 		KDUMP_ADDR=`grep CONFIG_PHYSICAL_START $KDUMP_CONFIG | sed "s/CONFIG_PHYSICAL_START=//"`
 		# compare the two
-		if [ "$KDUMP_ADDR" != "$IOMEM_ADDR" ] ; then
+		if [ $KDUMP_ADDR != $IOMEM_ADDR ] ; then
 			log_failure_msg "kdump kernel relocation address does not match crashkernel parameter"
 	        [ ! $DRY_RUN ] && exit 1;
 			return 1;
@@ -259,7 +307,7 @@ function kdump_load()
 	# Different kernel types allow/require different options:
 	# The only special case here is that x86, x86_64 elf style
 	# binaries require the --args-linux argument.
-	if [ "$ARCH" != "ia64" ] ; then
+	if [ $ARCH != "ia64" ] ; then
 		ELF_TST=`file $KDUMP_KERNEL | grep ELF`
 		if [ -n "$ELF_TST" ] ; then
 			KEXEC_CMD="$KEXEC_CMD --args-linux"
@@ -323,29 +371,6 @@ function kdump_unload()
 	fi
 }
 
-#
-# Return the name of the subdirectory to store core file.
-#	Will add hostname/IP according to the value of
-#	HOSTTAG if networked dump is selected
-
-function define_stampdir()
-{
-	STAMP=$1
-	HOSTTAG="${HOSTTAG:=ip}"
-
-	if [ -z "$SSH" ] && [ -z "$NFS" ]; then
-		echo "$KDUMP_COREDIR/$STAMP"
-	elif [ "$HOSTTAG" = "hostname" ];then
-		echo "$KDUMP_COREDIR/$(hostname)-$STAMP"
-	else
-		THIS_HOST="$(hostname -I)"
-		set -- $THIS_HOST
-		THIS_HOST=$1
-		echo "$KDUMP_COREDIR/$THIS_HOST-$STAMP"
-	fi
-}
-
-
 # Saving the vmcore:
 #	Our priorities are:
 #	  1. If the makedumpfile config link is valid, use that
@@ -353,222 +378,73 @@ function define_stampdir()
 #	  3. else fallback to using:  makedumpfile -d 1 -c
 #	  4. else use cp
 #
+# TODO: implement different transport options other than
+# store to local disk
+#
 # Returns: 0/1 (success/fail)
 # Sets: KDUMP_STAMPDIR, KDUMP_COREFILE
 function kdump_save_core()
 {
-	KDUMP_STAMP=`date +"%Y%m%d%H%M"`
-	KDUMP_STAMPDIR=$(define_stampdir $KDUMP_STAMP)
+	KDUMP_STAMPDIR="$KDUMP_COREDIR/"`date +"%Y%m%d%H%M"`
 	KDUMP_CORETEMP="$KDUMP_STAMPDIR/dump-incomplete"
-	KDUMP_COREFILE="$KDUMP_STAMPDIR/dump.$KDUMP_STAMP"
-	KDUMP_DMESGFILE="$KDUMP_STAMPDIR/dmesg.$KDUMP_STAMP"
+	KDUMP_COREFILE="$KDUMP_STAMPDIR/dump."`date +"%Y%m%d%H%M"`
+	KDUMP_DMESGFILE="$KDUMP_STAMPDIR/dmesg."`date +"%Y%m%d%H%M"`
 
-	# If we use NFS, verify that we can mount the FS
-	#
-	if [ -n "$NFS" ];then
-		log_action_msg "Mounting NFS mountpoint $NFS ..."
-		mount -t nfs -o nolock -o tcp -o soft -o timeo=5 -o retrans=5 $NFS $KDUMP_COREDIR
-		ERROR=$?
-		if [ $ERROR -ne 0 ];then
-			log_failure_msg "$NAME: Unable to mount remote NFS directory $NFS. Cannot save core"
-			logger -t $NAME "Unable to mount remote NFS directory $NFS. Cannot save core"
-			return 1;
-		fi
+	mkdir -p $KDUMP_STAMPDIR
 
-		# FS is mounted, see if we can write to it
-		#
-		mkdir -p $KDUMP_STAMPDIR
-		ERROR=$?
-
-		if [ $ERROR -ne 0 ];then
-			log_failure_msg "$NAME: Unable to write to the remote NFS directory $NFS. Cannot save core"
-			logger -t $NAME "Unable to write to the remote NFS directory $NFS. Cannot save core"
-			umount $KDUMP_COREDIR
-			UMNT_ERROR=$?
-			if [ $UMNT_ERROR -ne 0 ];then
-				log_failure_msg "$NAME: Unable to cleanly unmount the NFS file system"
-				logger -t $NAME "Unable to cleanly unmount the NFS file system"
-			fi
-		else
-			log_action_msg "Dumping to NFS mountpoint $NFS/$KDUMP_STAMP"
-			logger -t $NAME "Dumping to NFS mountpoint $NFS/$KDUMP_STAMP"
-		fi
+	DEBUG_KERNEL=`readlink -n -s $kernel_link`
+	if [ -e "$DEBUG_KERNEL" ] ; then
+		MAKEDUMP_ARGS=${MAKEDUMP_ARGS:="-c -d 31"}
+		MAKEDUMP_ARGS="$MAKEDUMP_ARGS -x $DEBUG_KERNEL"
 	else
-		mkdir -p $KDUMP_STAMPDIR
+		MAKEDUMP_ARGS=${MAKEDUMP_ARGS:="-c -d 1"}
 	fi
+
+	# Move previously linked kernel particulars into dump directory.
+	[ -e $kernel_link ] && mv $kernel_link $KDUMP_STAMPDIR
+	[ -e $kconfig_link ] && mv $kconfig_link $KDUMP_STAMPDIR
+	[ -e $systemmap_link ] && mv $systemmap_link $KDUMP_STAMPDIR
 
 	log_action_msg "running makedumpfile $MAKEDUMP_ARGS $vmcore_file $KDUMP_CORETEMP"
 	makedumpfile $MAKEDUMP_ARGS $vmcore_file $KDUMP_CORETEMP
-	ERROR=$?
-	if [ $ERROR -ne 0 ] ; then
+	if [ $? -ne 0 ] ; then
 		log_failure_msg "$NAME: makedumpfile failed, falling back to 'cp'"
 		logger -t $NAME "makedumpfile failed, falling back to 'cp'"
 		KDUMP_CORETEMP="$KDUMP_STAMPDIR/vmcore-incomplete"
-		KDUMP_COREFILE="$KDUMP_STAMPDIR/vmcore.$KDUMP_STAMP"
+		KDUMP_COREFILE="$KDUMP_STAMPDIR/vmcore."`date +"%Y%m%d%H%M"`
 		cp $vmcore_file $KDUMP_CORETEMP
-		ERROR=$?
 	fi
 
 	# did we succeed?
-	if [ $ERROR == 0 ]; then
+	if [ $? == 0 ]; then
 		mv $KDUMP_CORETEMP $KDUMP_COREFILE
 		log_success_msg "$NAME: saved vmcore in $KDUMP_STAMPDIR"
 		logger -t $NAME "saved vmcore in $KDUMP_STAMPDIR"
+		sync
 	else
 		log_failure_msg "$NAME: failed to save vmcore in $KDUMP_STAMPDIR"
 		logger -t $NAME "failed to save vmcore in $KDUMP_STAMPDIR"
 	fi
 
-	# dump the dmesg buffer
-	if [ "$KDUMP_DUMP_DMESG" -eq 1 ] ; then
-            log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE"
-            makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE
-            ERROR=$?
-            if [ $ERROR -ne 0 ] ; then
-                log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-                logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-            fi
-
-	    # did we succeed?
-	    if [ $ERROR == 0 ]; then
-		log_success_msg "$NAME: saved dmesg content in $KDUMP_STAMPDIR"
-		logger -t $NAME "saved dmesg content in $KDUMP_STAMPDIR"
-	    else
-		log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_STAMPDIR"
-		logger -t $NAME "failed to save dmesg content in $KDUMP_STAMPDIR"
-	    fi
-	fi
-	# If we use NFS, umount the remote FS
-	#
-	if [ -n "$NFS" ];then
-		umount $KDUMP_COREDIR
-		UMNT_ERROR=$?
-		if [ $UMNT_ERROR -ne 0 ] ; then
-			log_failure_msg "$NAME: Unable to cleanly unmount the NFS file system"
-			logger -t $NAME "Unable to cleanly unmount the NFS file system"
-		fi
-	fi
-
-	return $ERROR
-}
-
-function kdump_save_core_to_ssh()
-{
-	KDUMP_SSH_KEY="${SSH_KEY:=/root/.ssh/kdump_id_rsa}"
-	KDUMP_REMOTE_HOST="$SSH"
-
-	KDUMP_STAMP=`date +"%Y%m%d%H%M"`
-	KDUMP_STAMPDIR=$(define_stampdir $KDUMP_STAMP)
-
-	KDUMP_CORETEMP="$KDUMP_STAMPDIR/dump-incomplete"
-	KDUMP_COREFILE="$KDUMP_STAMPDIR/dump.$KDUMP_STAMP"
-	KDUMP_TMPDMESG="/tmp/dmesg.$KDUMP_STAMP"
-	KDUMP_DMESGFILE="$KDUMP_STAMPDIR/dmesg.$KDUMP_STAMP"
-	ERROR=0
-
-	ssh -i $KDUMP_SSH_KEY $KDUMP_REMOTE_HOST mkdir -p $KDUMP_STAMPDIR
-	ERROR=$?
-	# If remote connections fails, no need to continue
-	if [ $ERROR -ne 0 ] ; then
-		log_failure_msg "$NAME: Unable to reach remote server $KDUMP_REMOTE_HOST. No reason to continue"
-		logger -t $NAME "Unable to reach remote server $KDUMP_REMOTE_HOST. No reason to continue"
-		return 1
-	fi
-
-	# Add '-F' [flatten] to MAKEDUMP_ARGS, if not there:
-	[ "${MAKEDUMP_ARGS#-F*}" != "${MAKEDUMP_ARGS}" ] || MAKEDUMP_ARGS="${MAKEDUMP_ARGS} -F"
-	log_action_msg "sending makedumpfile $MAKEDUMP_ARGS $vmcore_file to $KDUMP_REMOTE_HOST : $KDUMP_CORETEMP"
-	makedumpfile $MAKEDUMP_ARGS $vmcore_file | ssh -i $KDUMP_SSH_KEY $KDUMP_REMOTE_HOST dd of=$KDUMP_CORETEMP
+	log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE"
+	makedumpfile --dump-dmesg $vmcore_file $KDUMP_DMESGFILE
 	ERROR=$?
 	if [ $ERROR -ne 0 ] ; then
-		log_failure_msg "$NAME: makedumpfile failed, falling back to 'scp'"
-		logger -t $NAME "makedumpfile failed, falling back to 'scp'"
-		KDUMP_CORETEMP="$KDUMP_STAMPDIR/vmcore-incomplete"
-		KDUMP_COREFILE="$KDUMP_STAMPDIR/vmcore.$KDUMP_STAMP"
-		scp -i $KDUMP_SSH_KEY $vmcore_file $KDUMP_REMOTE_HOST:$KDUMP_CORETEMP
-		if [ $? -ne 0 ];then
-			log_failure_msg "$NAME: makedumpfile scp failed. The vmcore file will  not be available"
-			logger -t $NAME "makedumpfile scp failed. The vmcore file will  not be available"
-		else
-			ERROR=0
-		fi
-	else
-		ERROR=0
+		log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
+		logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
 	fi
 
 	# did we succeed?
-	if [ $ERROR -ne 0 ]; then
-		log_failure_msg "$NAME: failed to save vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		logger -t $NAME "failed to save vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-	else
-		ssh -i $KDUMP_SSH_KEY $KDUMP_REMOTE_HOST mv $KDUMP_CORETEMP $KDUMP_COREFILE
-		log_success_msg "$NAME: saved vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		logger -t $NAME "saved vmcore in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-	fi
-
-	# dump the dmesg buffer
-        if [ "$KDUMP_DUMP_DMESG" -eq 1 ] ; then
-	    log_action_msg "running makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG"
-	    makedumpfile --dump-dmesg $vmcore_file $KDUMP_TMPDMESG
-	    ERROR=$?
-	    if [ $ERROR -ne 0 ] ; then
-		    log_failure_msg "$NAME: makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-		    logger -t $NAME "makedumpfile --dump-dmesg failed. dmesg content will be unavailable"
-	    else
-		    scp -i $KDUMP_SSH_KEY $KDUMP_TMPDMESG $KDUMP_REMOTE_HOST:$KDUMP_DMESGFILE
-		    ERROR=$?
-	    fi
-
-	    # did we succeed?
-	    if [ $ERROR == 0 ]; then
-		    log_success_msg "$NAME: saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		    logger -t $NAME "saved dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		    return 0;
-	    else
-		    log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		    logger -t $NAME "failed to save dmesg content in $KDUMP_REMOTE_HOST:$KDUMP_STAMPDIR"
-		    return 1;
-	    fi
-	fi
-}
-
-function kdump_propagate()
-{
-	KDUMP_SSH_KEY="${SSH_KEY:=/root/.ssh/kdump_id_rsa}"
-	KDUMP_REMOTE_HOST="$SSH"
-
-	# ssh key propagation is only needed
-	# if remote ssh dump is configured
-	if [ -z "$KDUMP_REMOTE_HOST" ];then
-		log_failure_msg "$NAME: Remote ssh dump is not configured. No reason to propagate"
-		logger -t $NAME "Remote ssh dump is not configured. No reason to propagate"
-		return 1;
-	fi
-
-	# Verify if the provided key exists and create it if needed
-	if [ -f "$KDUMP_SSH_KEY" ];then
-		echo "Using existing key $KDUMP_SSH_KEY"
-	else
-		echo "Need to generate a new ssh key..."
-		/usr/bin/ssh-keygen -t rsa -f $KDUMP_SSH_KEY -N "" 2>&1 > /dev/null
-	fi
-
-	KDUMP_SSH_USER=${KDUMP_REMOTE_HOST%@*}
-	KDUMP_SSH_TARGET=${KDUMP_REMOTE_HOST#*@}
-
-	ssh-copy-id -i $KDUMP_SSH_KEY $KDUMP_SSH_USER@$KDUMP_SSH_TARGET &>/dev/null
-	ERROR=$?
-
-	if [ $ERROR -ne 0 ];then
-		log_failure_msg "$NAME: $KDUMP_SSH_KEY failed to be sent to $KDUMP_REMOTE_HOST"
-		logger -t $NAME "$KDUMP_SSH_KEY failed to be sent to $KDUMP_REMOTE_HOST"
-		return 1;
-	else
-		logger -t $NAME "propagated ssh key $KDUMP_SSH_KEY to server $KDUMP_REMOTE_HOST"
-		echo "propagated ssh key $KDUMP_SSH_KEY to server $KDUMP_REMOTE_HOST"
+	if [ $ERROR == 0 ]; then
+		log_success_msg "$NAME: saved dmesg content in $KDUMP_STAMPDIR"
+		logger -t $NAME "saved dmesg content in $KDUMP_STAMPDIR"
+		sync
 		return 0;
+	else
+		log_failure_msg "$NAME: failed to save dmesg content in $KDUMP_STAMPDIR"
+		logger -t $NAME "failed to save dmesg content in $KDUMP_STAMPDIR"
+		return 1;
 	fi
-
 }
 
 
@@ -577,6 +453,7 @@ case "$1" in
   test)
 	DRY_RUN="true"
 	check_kdump_support;
+	locate_debug_kernel;
 	locate_kdump_kernel;
 	kdump_load;
 	kdump_test
@@ -588,6 +465,7 @@ case "$1" in
 	;;
   load)
 	check_kdump_support;
+	locate_debug_kernel;
 	locate_kdump_kernel;
 	kdump_load;
 	;;
@@ -604,21 +482,14 @@ case "$1" in
 	exit 0;
 	;;
   savecore)
-	if ! [ -z $SSH ];then
-		kdump_save_core_to_ssh
-	else
-		kdump_save_core
-	fi
+	kdump_save_core
 	exit $?
-	;;
-  propagate)
-	kdump_propagate;
 	;;
   help|-h*|--h*)
 	kdump_help
 	;;
   *)
-	echo "Usage: $0 {help|test|show|status|load|unload|savecore|propagate}"
+	echo "Usage: $0 {help|test|show|status|load|unload|savecore}"
 	exit 1
 	;;
 esac
